{{- if .Values.remediation.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tigergate.remediatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tigergate.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tigergate.fullname" . }}-remediate
  labels:
    {{- include "tigergate.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tigergate.fullname" . }}-remediate
  labels:
    {{- include "tigergate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tigergate.fullname" . }}-remediate
subjects:
  - kind: ServiceAccount
    name: {{ include "tigergate.remediatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tigergate.fullname" . }}-remediate-read
  labels:
    {{- include "tigergate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tigergate.fullname" . }}-read
subjects:
  - kind: ServiceAccount
    name: {{ include "tigergate.remediatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
